### ISSUE TITLE
spec: clarify pod uuids

### ISSUE THREAD

**Issue by jonboulle** [appc/spec#103]
[CRMs](https://github.com/appc/spec/blob/master/SPEC.md#container-runtime-manifest-schema) have a **uuid** but it is underspecified; we should explicate the purpose and how it might be generated.

Also, in the [metadata server](https://github.com/appc/spec/blob/master/SPEC.md#container-metadata) it's referred to as *uid*, so this should be changed to *uuid* for consistency.

**Comment by jonboulle** [comment]
Another aspect to this is that since UUIDs are "practically unique" and not "guaranteed unique" we might want to document the theoretical possibility of a conflict, particularly when it comes to the identity verification in the metadata service. 

Extremely security-conscious implementations of the spec would likely leverage a genuine (shared/distributed) unique ID rather than just generating a UUID locally in the executor.

**Comment by eyakubovich** [comment]
UUIDs are conceptually unique in time and space. The whole point of using them is that you don't worry that they're not. All types, if properly implemented, are unique enough that you don't have to concern yourself otherwise. If you're worried about probabilities on those scales, then most of cryptography in use is broken anyway and "extremely security conscious" couldn't even use encrypt their data.

**Comment by jonboulle** [comment]
Sure, assuming "properly implemented", but there are also other reasons a centralised generator is useful, e.g. auditing/policy.

Anyway, feel free to do the wordsmithing to your own satisfaction :-)

updated references:
https://github.com/appc/spec/blob/de93ed4e7c40739b90011fdc4d93553417f0d9f3/SPEC.md#pod-uuid
https://github.com/appc/spec/blob/de93ed4e7c40739b90011fdc4d93553417f0d9f3/SPEC.md#metadata-service

**Comment by jonboulle** [comment]
better covered by #324
