### ISSUE TITLE
Add some high level info to README about what the spec is and how it might be relevant to people

### ISSUE THREAD

**Issue by nchammas** [appc/spec#177]
For the new visitor, the [Overview](https://github.com/appc/spec#overview) section of the README doesn't answer some basic questions one might have.

Perhaps we don't want to add any more information to the README, but as a total newcomer to the project it would be nice to be able to find quick answers to questions like:

* What is the App Container spec? (In addition to the existing answer to "What does this repository contain?")
* I know a bit about Docker and containers in general. Why is this project relevant or interesting to me?
* What is the promise of the App Container Spec? Is it, build an image once, run it on any number of implementations?
* What are some implementations of the spec?

Perhaps this kind of stuff belongs in a blog post as opposed to the README, but I thought I'd raise this here to see what people think.

**Comment by philips** [comment]
This is a good idea. I will take a shot at it below:

> What is the App Container spec? (In addition to the existing answer to "What does this repository contain?") I know a bit about Docker and containers in general. Why is this project relevant or interesting to me?


The App Container (appc) is a well-specified community developed specification to define an image format, runtime environment and discovery mechanism for application containers. An application container is a way of packaging and executing processes on a computer system that isolates the application from changes to the underlying host OS. For example an application packaged as a container would bring its own copy of a python runtime, shared libraries and application code and would not share those packages with the host.

App containers are useful because they put developers in full control of the exact versions of software dependencies for their applications. This reduces surprises from dev, test and prod while freeing the underlying OS from worrying about shipping software specific to the applications it will run. This decoupling of concerns increases the ability for the OS and application to be serviced for updates and security patches.

For these reasons we want the world to run containers. A world where your application can be packaged once, and ran in the environment you choose. The App Container (appc) spec aims to have the following properties:

- Composable. All tools for downloading, installing, and running containers should be well integrated, but independent and composable.
- Security. Isolation should be pluggable, and the crypto primitives for strong trust, image auditing and application identity should exist from day one.
- Image distribution. Discovery of container images should be simple and facilitate a federated namespace, and distributed retrieval. This opens the possibility of alternative protocols, such as BitTorrent, and deployments to private environments without the requirement of a registry.
- Open. The format and runtime should be well-specified and developed by a community. We want independent implementations of tools to be able to run the same container consistently.

> What is the promise of the App Container Spec? Is it, build an image once, run it on any number of implementations?

By explicitly defining how an app is packaged into an image, downloaded over a network, and executed as a container outside of a particular implementation we hope to enable a community of engineers to build tooling around the fundamental building block of a container. Some examples of build systems and tools that have been built so far include:

- ACI builder for Go projects https://github.com/jonboulle/goaci
- ACI builder from docker images https://github.com/appc/docker2aci

> What are some implementations of the spec?

The most mature implementation of the spec today is (Rocket)[https://github.com/coreos/rocket] but other implementations are being built too:

- Jet Pack (Freebsd/Go) https://github.com/3ofcoins/jetpack
- libappc (C++ library) https://github.com/cdaylward/libappc
- Nose Cone (Linux/C++) https://github.com/cdaylward/nosecone 
- Rocket (Linux/Go) https://github.com/coreos/rocket

/cc @polvi @robszumski @jonboulle Anything else I should add?

**Comment by jonboulle** [comment]
No, that looks good - I actually had started a FAQ.md on my local system a long time ago for this exact reason but never added it to git :-(

This is a good starting point, put it up and we can go from there...

**Comment by philips** [comment]
@jonboulle I merged it since it is way better than the current state. Thanks for the suggestion @nchammas.

**Comment by nchammas** [comment]
@philips This is great!

Your writeup gives me precisely the mental model I need to understand what appc and containers are all about, and I think it will be very valuable for newcomers to the project.

Thank you for taking the time to write it up.
