### ISSUE TITLE
Specify how to handle usernames and uids in ACIs (and groupnames & gids)

### ISSUE THREAD

**Issue by alban** [appc/spec#231]
The spec should talk about user ids and group ids in containers.

ACIs contain ownership information about the files in two different forms:
- uid and gid: numbers (mandatory fields)
- username and groupname: strings (optional fields)

When the tarball is extracted, the mapping between uid/gid and username/groupname is lost. The spec does not mention whether to use uid/gid or username/groupname.

An ACI might not contain any /etc/passwd file.

If a container contains one mysql app and one apache app, they might want to run as users mysql and www-data respectively. The files in the apache aci might belong to user ID 33 but unless apache.aci contains /etc/passwd, uid=33 does not mean anything.

This issue was first mentioned in:
- https://github.com/appc/spec/pull/207#issuecomment-77173130
- https://github.com/coreos/rocket/issues/539#issuecomment-77167768

**Comment by smarterclayton** [comment]
We are about to start adding [security contexts](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/security_context.md) to Kubernetes - the goals are to ensure the execution environment can be fully specified in a way that allows effective cross cluster resource sharing (fs, primarily).  The draft spec I linked is the pre implementation and I'm sure there are gotchas in the way.  A tradeoff we discussed is whether to be generic "run securely" or specific "run as this uid".  The doc leans more towards the latter, as it can be automatically inferred from the context in which pods are executed.

**Comment by alban** [comment]
@smarterclayton : thanks for the notification. Is there a GitHub issue or a PR to follow the security contexts development in Kubernetes?

**Comment by smarterclayton** [comment]
Not yet but when it exists I will cc it here.

----- Original Message -----

**Comment by philips** [comment]
I think that running as a particular UID or UID based on filepath owner are the best options and currently in the spec. An external database, such as `/etc/passwd`, is too difficult to reason about and fix-up across multiple containers, if needed.

@jonboulle I think we should remove the ability to specify a "username" or "groupname" in the current spec. I had forgotten that was in there.

**Comment by jheiss** [comment]
@philips: Regarding running as a filepath owner, is the idea that the ACI gets unpacked as the user you want it to run as, so all of the unpacked files are owned by that user?

**Comment by alban** [comment]
I was told that some applications use `getpwuid(getuid())` and this will not work in a container if NSS relies on `/etc/passwd` and it is not there. I don't know if the spec should do something about that?

**Comment by krobertson** [comment]
I'm using getpwuid in a soon to be releases implementation, but its only possible since its done from within the container. But otherwise if the process wasnt in the mount namespace and already chrooted, it would use the hosts /etc/passwd.

Previously, we had looked it up at the host level and used a line reader to process it.

**Comment by ecnahc515** [comment]
I just want to bring up the point that we should really consider the implications of how this will play with user namespaces. On Linux you have to provide a mapping of host uid/gid's to container uid/gid's. This also has implications with file permissions on the container FS since they'll be owned by the host IDs, rather than container IDs.

I know we don't want to make appc directly specific to Linux, but Linux you end up with some very specific constraints when trying to implement user/group isolation when using Linux.

Just wanted to bring this up.

**Comment by krobertson** [comment]
One thing to handle user namespaces right is to extract the image file with the uid mappings applied. If the mapping for root was 100000 instead of 0, we just added 100000 to any uid/gid. We rolled out user namespace support in Apcera's containers almost a year ago and this worked well. It would look weird to the host, but not the container, and is more or less outside of the spec as an implementation detail for how it'll enforce the security it chooses to.

**Comment by alban** [comment]
> One thing to handle user namespaces right is to extract the image file with the uid mappings applied. If the mapping for root was 100000 instead of 0, we just added 100000 to any uid/gid.

Would the uid mapping defined statically in the image manifest, or would it be dynamically defined when a new pod is started? When the same ACI is executed several times simultaneously, would we use the same uid mapping, or a different uid mapping for each pod?

In order to isolate pods from each others, it would be better to use different mappings.

But when the executor uses overlayfs, the image not extracted for each execution but only one time when the image is fetched. The extracted files are stored once in the cache tree and the same directory from the cache tree is used as overlayfs lowerdir for all pods using that ACI. So unless overlayfs gets [some dynamic uid-shifting feature](http://lists.freedesktop.org/archives/systemd-devel/2015-February/027880.html), we cannot use both dynamic uid mappings and overlayfs.

**Comment by smarterclayton** [comment]
> On Apr 28, 2015, at 6:59 AM, Alban <notifications@github.com> wrote:
> 
> One thing to handle user namespaces right is to extract the image file with the uid mappings applied. If the mapping for root was 100000 instead of 0, we just added 100000 to any uid/gid.
> 
> Would the uid mapping defined statically in the image manifest, or would it be dynamically defined when a new pod is started? When the same ACI is executed several times simultaneously, would we use the same uid mapping, or a different uid mapping for each pod?
> 
> In order to isolate pods from each others, it would be better to use different mappings.
> 
That had been the plan for Kube in MT mode with userns.
> But when the executor uses overlayfs, the image not extracted for each execution but only one time when the image is fetched. The extracted files are stored once in the cache tree and the same directory from the cache tree is used as overlayfs lowerdir for all pods using that ACI. So unless overlayfs gets some dynamic uid-shifting feature, we cannot use both dynamic uid mappings and overlayfs.
> 
Could the presence of a user mapping range be a signal to the cache tree that the image needs to be cached by imageid+uidrange?

**Comment by krobertson** [comment]
Mappings should likely be up to the host to decide rather than allow them to be specified by the ACI. However it is also hard to apply as a blanket rule when the container needs to access things externally. For instance, we do some basic work with shared storage over NFS, and ownership/permissions can be tricky because the NFS server sees files by the host's UID, not the container's.  So a file created by root inside the container is owned by like 100000 on the NFS server.

Some of the trade offs between things like external storage, file deduping, etc. should be up to the ACE implementation rather than in the spec, IMO.

An implementation that high container isolation may opt for dynamic mappings over dedupping files. An implementation may be on the opposite side as well.

Even in the linked mailing list, the uid shifting filesystem is something I'm almost to the point of trying to contract out for someone to implement. It would be useful for package caches to use a static mapping, and to have the actual container mounts be shifted. That way you get both.
