### ISSUE TITLE
what's the relation between appc and docker-libcontainer?

### ISSUE THREAD

**Issue by HuKeping** [appc/spec#430]
Are these two on the same aspect? If not then what's the counterpart in appc

**Comment by krobertson** [comment]
AppC is strictly a specification of a container format. It defines a format for a container image, and a JSON document defining the container (what to run, who to run it as, etc), which is the ACI. It defines some baseline requirements of an implementation (ACE, App Container Executor) which would actually run the containers, and so forth.

Libcontainer is the actual container orchestration/iimplementation within Docker. The equivalent within AppC would be one of the AppC implementations (ACE, App Container Executors) like rkt, kurma, etc (list: https://github.com/appc/spec#what-are-some-implementations-of-the-spec).

Docker doesn't quite have an equivalent to AppC. It has a few loose specs, but primarily focuses on being an implementation rather than a specification.

**Comment by HuKeping** [comment]
Thanks @krobertson

**Comment by jonboulle** [comment]
Please re-open if you have further questions. Thanks.

**Comment by HuKeping** [comment]
Hi @krobertson , If my company build an implementation of AppC, let's call it rkt2. Does it mean that the images made by rkt2 can be run by rkt or any other implementations of AppC consistently?

**Comment by jonboulle** [comment]
@HuKeping Yes, that is the intention of the spec.

**Comment by HuKeping** [comment]
amazing! So that is what we want, thanks @jonboulle

**Comment by HuKeping** [comment]
hi, another question, are these `[Isolators](https://github.com/appc/spec/blob/master/spec/ace.md#linux-isolators)` all or portion based on 
cgroups?

**Comment by krobertson** [comment]
They vary on how the actual orchestration of them are. cgroups is good for things around resource limits on cpu, memory, iops, etc. Other tools would be needed for traffic shaping or network bandwidth. Isolators are meant to be just a generic way to specify a constraint to be placed on a container. They will vary, and are why they are kind of namespaced (ie, "os/linux/capabilities-remove-set", since that is something unique to linux and not applicable to freebsd).

For cgroups, there are different cgroups mounts that you can have, like cpu, cpuset, memory, devices, etc. And each one adds various sets of functionality.

One like `capabilities-retain-set` are provided through linux capabilities (http://linux.die.net/man/7/capabilities).

Other things like network bandwidth are maybe done with `tc` (http://www.lartc.org/manpages/tc.txt).

They aren't unique to cgroups at all, or strictly tied to it, since cgroups is linux specific.

**Comment by HuKeping** [comment]
Thanks @krobertson
