### ISSUE TITLE
ace: validator fails to detect mount points

### ISSUE THREAD

**Issue by iaguis** [appc/spec#464]
Currently, the ACE validator checks if `/db` is a mount point since [it's defined as a mount point in the manifest](https://github.com/appc/spec/blob/0d1edc37553152577a56f256279992200f142b48/ace/image_manifest_main.json#L37).

It checks it's a mount point by calling `statfs()` on the directory and the parent and then comparing the f_fsid field. This check doesn't detect if a directory is a bind mount so it will error out mistakenly when the mount point is in the same filesystem as the parent:

```
# mkdir a b
# mount --bind a b
# stat --file-system b
File: "b"
    ID: df4743518d77c185 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 116580597  Free: 32241161   Available: 32237065
Inodes: Total: 29622272   Free: 28560905
# stat --file-system b/..
File: "b/.."
    ID: df4743518d77c185 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 116580597  Free: 32241161   Available: 32237065
Inodes: Total: 29622272   Free: 28560905
```

We could use [`name_to_handle_at()`](http://man7.org/linux/man-pages/man2/open_by_handle_at.2.html) or the [`mnt_id` flag in `/proc/[pid]/fdinfo/[fd]`](http://man7.org/linux/man-pages/man5/proc.5.html) but the former is not included in all kernels and the latter was added in Linux 3.15.

**Comment by mpasternacki** [comment]
I bumped into a similar issue on FreeBSD: the `Fsid` fields were zeroed. I'm not 100% sure whether it's because of bind mount, or because jail is not allowed to see the fields. I've got a monkey-patch in Jetpack for that (https://github.com/3ofcoins/jetpack/commit/b4b599e697572d851d82163be1117d20336d971b) and I want to make a proper pull request. Not sure whether this approach would work on Linux, though: it seems to me that the `Statfs_t` fields I'm using are not available on Linux, but this may provide a direction to work from.

**Comment by iaguis** [comment]
It seems we can't use [`name_to_handle_at()`](http://man7.org/linux/man-pages/man2/open_by_handle_at.2.html) because it requires `CAP_DAC_READ_SEARCH`.

I think what we should do here is try to use [the `mnt_id` test](http://man7.org/linux/man-pages/man5/proc.5.html) and if it doesn't work because we have an old Linux, simply skip the test. There's no way to detect if it's a bind mount or not so the test doesn't make sense.
