### ISSUE TITLE
[HELP] how to manifest static file paths?

### ISSUE THREAD

**Issue by gyuho** [appc/spec#480]
My environment:

```
Linux ubuntu 3.16.0-48-generic #64~14.04.1-Ubuntu SMP Thu Aug 20 23:03:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
model name	: Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
```

<hr>
<br>

Hello,

I am trying to replicate this sample example:
https://github.com/coreos/rkt/blob/master/Documentation/getting-started-guide.md

based on https://github.com/appc/spec/blob/af37e649406ed74eb55940a9bbd217911b0f9aee/spec/aci.md

The simple example works but when I try to add static files with `rkt`, it crashes as follows:

```
$ sudo ./rkt --insecure-skip-verify run code-0.0.1-linux-amd64.aci;
2015/09/04 04:06:46 Preparing stage1
2015/09/04 04:06:47 Writing image manifest
2015/09/04 04:06:47 Loading image sha512-783fcdf0db652b563b43274c6c27fcfafec5f7bf806d0f226522e4d2a3fdca12
2015/09/04 04:06:47 Writing pod manifest
2015/09/04 04:06:47 Setting up stage1
2015/09/04 04:06:47 Wrote filesystem to /var/lib/rkt/pods/run/bf98be3d-34cf-4efd-bd49-eecfa763d10d
2015/09/04 04:06:47 Pivoting to filesystem /var/lib/rkt/pods/run/bf98be3d-34cf-4efd-bd49-eecfa763d10d
2015/09/04 04:06:47 Execing /init
Failed to generate nspawn args: no volume for mountpoint "static" in app "code".
```

<br>
There must be wrong in my `manifest.json`.

<br>
First, here's my source tree:

```
static/
    js/
    img/
templates/
    base.html
    main.html
main.go

rkt
actool
stage1.aci
stage1-lkvm.aci
manifest.json
code

code-layout/
    manifest
    rootfs/
        bin/
            static/
            templates/
            code
```

<br>
Second, here's `manifest.json`:

```json
{
	"acKind": "ImageManifest",
	"acVersion": "0.6.1",
	"name": "gyuho/code",
	"labels": [
		{
			"name": "version",
			"value": "0.0.1"
		},
		{
			"name": "arch",
			"value": "amd64"
		},
		{
			"name": "os",
			"value": "linux"
		}
	],
	"app": {
		"user": "root",
		"group": "root",
		"exec": [
			"/bin/code"
		],
		"mountPoints": [
			{
				"name": "static",
				"path": "/bin/static"
			},
			{
				"name": "templates",
				"path": "/bin/templates"
			}
		],
		"ports": [
			{
				"name": "web-server",
				"protocol": "tcp",
				"port": 8080
			}
		]
	},
	"mounts": [
		{"volume": "static", "mountPoint": "static"},
		{"volume": "templates", "mountPoint": "templates"}
	],
	"annotations": [
		{
			"name": "authors",
			"value": "Gyu-Ho Lee <gyuho.cs@gmail.com>"
		}
	]
}

```

<br>
Third, here's my build script:

```sh
CGO_ENABLED=0 GOOS=linux go build -o code -a -installsuffix cgo .;
file code;
ldd code;
sudo ./actool --debug validate manifest.json;

mkdir -p code-layout/rootfs;
mkdir -p code-layout/rootfs/bin;

cp manifest.json code-layout/manifest;

cp code code-layout/rootfs/bin;
cp -rf static/ code-layout/rootfs/bin;
cp -rf templates/ code-layout/rootfs/bin;

sudo ./actool build --overwrite code-layout/ code-0.0.1-linux-amd64.aci;
sudo ./actool --debug validate code-0.0.1-linux-amd64.aci;

sudo ./rkt metadata-service  &
sudo ./rkt --insecure-skip-verify run code-0.0.1-linux-amd64.aci;
```

It crashes with the last command: `sudo ./rkt --insecure-skip-verify run code-0.0.1-linux-amd64.aci;`

**What am I doing wrong here?**

`Dockerfile`, we have `WORKDIR` to set the working directory, and we `ADD` static files to that working directory. In the App Container Specification, **what is the best way to specify static file paths in `manifest.json`**?

Thanks!

**Comment by jonboulle** [comment]
Hey @gyuho, 

My first observation is that it looks like you might be conflating the [image manifest](https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema) with the [pod manifest](https://github.com/appc/spec/blob/master/spec/pods.md#pod-manifest-schema). The `mounts` array should be in the latter, but you have it in your example:
```
    "mounts": [
        {"volume": "static", "mountPoint": "static"},
        {"volume": "templates", "mountPoint": "templates"}
    ],
``` 

This section, mapping volumes to mountPoints, is actually part of the pod manifest. In standard use, rkt will automatically generate a pod manifest for you at runtime, so you don't need to write it yourself. In your case, rkt is failing execution because you have mountpoints specified in the image manifest but aren't giving it any volumes to map to these mountpoints. You can see some examples of how you would use rkt to mount volumes into the pod [here](https://github.com/coreos/rkt/blob/master/Documentation/subcommands/run.md#mount-volumes-into-a-pod).


**However**.. I'm a bit unclear on your example because I don't see a need for you to use mounts or volumes at all. Given that you've copied all the files you need into the image, it should be entirely self-contained and you can just remove the mounts and mountPoints sections from your image manifest entirely. Can you give that a try and let us know how you go? Mounts are only necessary if you want to dynamically add a volume to a pod at runtime. 

Does that help clear things up at all?

**Comment by gyuho** [comment]
@jonboulle  Thanks a lot for explanation.

I come from Docker background trying to do the same things with rkt and appc.
Yes, that's what I thought. I don't think I need to specify any static file paths.
Here's the Dockerfile that works for the same project:

```
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y nginx
ADD ./nginx.conf /etc/nginx/sites-available/default
RUN service nginx restart

# automatically copies the package source,
# fetches the application dependencies
# builds the program, and configures it to run on startup.
FROM golang:onbuild
EXPOSE 8080
```


I think I misunderstood this line:

> The on-disk layout of an App Container Image is straightforward.
> It includes a rootfs directory **with all of the files that will exist in the root
> of the app**, and an app image manifest file describing the contents of the 
> image and how to execute the app.
>
> https://github.com/appc/spec/blob/master/spec/aci.md#image-layout

This sounds like to me, even all static files need to be copied into `rootfs`.
I will research more tonight and come back to this.

**Comment by jonboulle** [comment]
@gyuho correct, in your simple example all static files would be in a single rootfs. There are a couple of alternative ways to achieve a similar thing, though:
- the static files could be located in a dependent image rather than in the same image as your code.
- if the static files _were_ located on another volume, you could use mountPoints/volumes to provide them into the pod at runtime, kinda like you were trying to do

**Comment by gyuho** [comment]
I understand. Thanks @jonboulle. 

I read https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema
again and made some changes to my `manifest.json` but still couldn't get it to run.
I think I am doing something run with my `rkt` paths.

I am getting follow errors:

```
2015/09/15 22:05:11 Preparing stage1

2015/09/15 22:05:11 Writing image manifest
2015/09/15 22:05:11 Loading image sha512-5fdcddc92a26a65269f7a5ebaf1c5aeff92627162b74ca5495d0c46872af4dde
2015/09/15 22:05:11 Writing pod manifest
2015/09/15 22:05:11 Setting up stage1
2015/09/15 22:05:11 Wrote filesystem to /var/lib/rkt/pods/run/5d9c2e4c-76f0-4868-95ec-86c24f219176
2015/09/15 22:05:11 Pivoting to filesystem /var/lib/rkt/pods/run/5d9c2e4c-76f0-4868-95ec-86c24f219176
2015/09/15 22:05:11 Execing /init
Failed to stat /usr/bin/static: No such file or directory
```

from this file system:

https://github.com/gyuho/learn/tree/master/doc/go_web_application_deploy_container/code


And I just copied `rkt`, `actool` binaries to this `code` directory when I run this build script:

https://github.com/gyuho/learn/blob/master/doc/go_web_application_deploy_container/code/deploy_with_rkt.sh

I think I need more readings on `rkt` now.

Thanks a lot for your help again!

**Comment by jonboulle** [comment]
Hey @gyuho , I'm going to close you out and point you in the direction of the soon-to-land acbuild: appc/acbuild#11 . It should make the build process much more straightforward for you, and if it doesn't cover your use case we'd love to hear your back there :-)

**Comment by gyuho** [comment]
@jonboulle thanks for keeping me updated on this. I will definitely try accbuild and come back to this if I still have any issue. Thanks!
