### ISSUE TITLE
spec: confused by Isolator struct

### ISSUE THREAD

**Issue by ChengTiesheng** [appc/spec#510]
Hi dear all,
    When I use the struct Isolator, I am a little confused by its definition. There is a member ValueRaw *json.RawMessage in the struct, but I don't know how to assign a value for it. If it is used  arbitrarily, how would appc runtime parse it?  Futhermore, when ValueRaw is used, the unit for the object is unkown, see the example as below, what is the unit for 200
"isolators": [
            {
                "name": "resource/cpu",
                "value": {"limit": "200"}
            }
        ], 
    What is more, I found isolator is designed a little complex that I don't know how to use it effectivly. If it was designed in a simple and straightforward way, I think it would be better and I will love it more:)
    The above mentioned is only my opinion, perhaps it is because I have not understood the inner design idea, if I have misunderstanding, please point it out.
    I need a help to understand how to use isolator struct effectivly, looking forward to your reply, thanks a lot.

Best regards,
Tiesheng

**Comment by jonboulle** [comment]
I agree that this struct is too complex and I would also like to see it made easier to use. The idea of the RawMessage is to (in principle) facilitate the addition of new isolator types, since the spec defines the type as being of arbitrary value: https://github.com/appc/spec/blob/master/spec/types.md#isolator-type

Currently the only way to instantiate an isolator is by unmarshalling a string. See https://github.com/appc/spec/issues/268 . A patch would gladly be welcome for that one.

**Comment by jonboulle** [comment]
You can see an example of how we work around this right now in rkt: https://github.com/coreos/rkt/blob/d6c8a33f04a28795e623bfb2b2bc245fb921763f/tests/rkt_run_pod_manifest_test.go#L345

**Comment by ChengTiesheng** [comment]
@jonboulle Got it, thanks so much for your detailed reply.

**Comment by ChengTiesheng** [comment]
Resolved, thanks so much.
