### ISSUE TITLE
appc/spec is not go-gettable

### ISSUE THREAD

**Issue by iaguis** [appc/spec#587]
```
> GOPATH=/home/iaguis/temp/gopath go get github.com/appc/spec/...
package github.com/appc/spec/ace
	imports github.com/camlistore/go4/errorutil: code in directory /home/iaguis/temp/gopath/src/github.com/camlistore/go4/errorutil expects import "go4.org/errorutil"
```

**Comment by sgotti** [comment]
Introduced in #578 

What about dropping go compiler < 1.5 support and start using golang vendoring?

It's default for latest godep. I also started using glide with flattened vendor tree since it support semver and other goodies. I explained my workflow, pro and cons here (updated in the latest comment) appc/acbuild#186

**Comment by steveeJ** [comment]
The problem is that github.com/camlistore/camlistore/pkg/errorutil is not available anymore. I'm not sure why godep doesn't use the stored revision though, which should definitely still have that path.

**Comment by iaguis** [comment]
https://github.com/camlistore/go4/pull/15
