### ISSUE TITLE
Allow capitalized letters in ACIdentifier/ACName type?

### ISSUE THREAD

**Issue by yifan-gu** [appc/spec#588]
Currently, the ACIdentifier(https://github.com/appc/spec/blob/master/spec/types.md#ac-identifier-type) and ACName(https://github.com/appc/spec/blob/master/spec/types.md#ac-name-type) are more strict than the RFCs, as they don't allow upper-case letters as we made the rule based on k8s's DNS_LABEL types.
However, both RFCs they based allow upper-case letters, so I don't know why we should not allow them.
One use case would be making the annotation keys compatible to docker labels.

Ref https://github.com/kubernetes/kubernetes/issues/23706

cc @jonboulle @thockin @sjpotter @random-liu

**Comment by thockin** [comment]
We made a choice to exclude uppercase letters in names for simplicity (well
before Docker did theirs).  Changing it now is a somewhat incompatible API
change (imagine an older kubectl and a newer apiserver, `kubectl edit` can
read an uppercase, and try to submit it but fail because it does
client-side validation.  Buggy as that is, it is real.

I don't think "be compatible with people who violate the recommended use"
is a strong argument for a change.

**Comment by yujuhong** [comment]
We are already fixing https://github.com/kubernetes/kubernetes/issues/23706 in  https://github.com/kubernetes/kubernetes/pull/23725 by switching all labels to lowercase letters, so there is not much to gain for appc to make the change.
