### ISSUE TITLE
HTTP_PROXY support broken by --insecure-options=all

### ISSUE THREAD

**Issue by alban** [appc/spec#609]
Capturing https://github.com/coreos/rkt/issues/2590#issuecomment-220983720:

> From the logs, HTTP_PROXY is used by the discovery but not for the download itself.
> 
> ```
> $ git grep ProxyFromEnvironment
> Godeps/_workspace/src/github.com/appc/spec/discovery/http.go:           Proxy: > http.ProxyFromEnvironment,
> ```
> 
> It seems that the `--insecure-options=all` breaks the proxy feature there:
> https://github.com/appc/spec/blob/master/discovery/http.go#L69
> 
> ```
> 	ClientInsecureTLS = &http.Client{
> 		Transport: &tInsecureTLS,
> 	}
> ```
> 
> The http.Transport is overwritten without the proxy.

**Comment by jonboulle** [comment]
but why? It should be a straight copy...

**Comment by jonboulle** [comment]
I mean tInsecureTLS is a copy of t after the Proxy func has been set.

**Comment by jellonek** [comment]
Exactly as in https://github.com/coreos/rkt/pull/2354

**Comment by jonboulle** [comment]
@jellonek can you elaborate? I don't understand what's going on here

**Comment by jellonek** [comment]
Instead of updating `Transport` in `http.DefaultClient`, there is constructed new `http.Client` which does not have proxy support (but `http.DefaultClient` have it).

@krnowak am I correct?

**Comment by krnowak** [comment]
@jell: The proxy support is in transport itself, see https://golang.org/src/net/http/transport.go#L33 (the `Proxy` member of the transport). So in this case, the `tInsecureTLS` variable should ideally be a copy of `http.DefaultTransport` with its `TLSClientConfig` updated to have the `InsecureSkipVerify` field set to true.

I'm not entirely sure if this is the case here, because we set the `Proxy` field of our transport to `http.ProxyFromEnvironment`, see https://github.com/appc/spec/blob/master/discovery/http.go#L57.

**Comment by jellonek** [comment]
ACK

**Comment by Jell** [comment]
@jell => @jellonek :) cheers

**Comment by jellonek** [comment]
Sry for inconvenience, i'm using this nickname (as a shortcut for this older one, longer one) on IRC.

**Comment by s-urbaniak** [comment]
The fetching logic not respecting `HTTP_PROXY` is not in appc, but in rkt itself. The bug is being addressed in https://github.com/coreos/rkt/pull/3303.

For completeness it is worth mentioning that recently appc was patched for `go vet` compliance explicitely setting `http.ProxyFromEnvironment` in the secure, and insecure clients in [1], and [2].

So I am inclined to close this issue, once the above mentioned PR is merged. 

[1] https://github.com/appc/spec/blob/f8bc8a9b07062dd28aedd522d869a0a9e822b4d4/discovery/http.go#L60
[2] https://github.com/appc/spec/blob/f8bc8a9b07062dd28aedd522d869a0a9e822b4d4/discovery/http.go#L72
