### ISSUE TITLE
spec: clarify relationship between CRM and ACE

### ISSUE THREAD

**Issue by jonboulle** [appc/spec#83]
There is a possible conflation between the CRM and the ACE runtime environment, which might need to be teased apart. In the lifecycle of an app image, between the points of "image manifest creation" (when it is bundled into an ACI) and "application execution" (when the ACE actually executes app(s) in a container), there are conceptually two points at which parameters from the image manifest can potentially be overridden/extended:
    1. when the CRM is generated 
    2. at runtime by the ACE

Currently, in rocket, we generate a CRM at runtime and use that as the final artefact to be executed (let's call that the _executed unit_). That is, rocket essentially conflates 1) and 2), by encoding all of its "ACE overriding" into the generated CRM. 

There is a lot of value in this model because it means the CRM is essentially immutable, and so for a given executor, two invocations of the same CRM should be effectively identical. (It also makes it convenient because the executor can make various assumptions about the environment - for example where images are located, whether they are unique, etc - when generating the CRM.

However, critically, it makes it impossible to use CRMs as a portable config (let's call that a _deployable unit_), because it inherently contains executor-specific information.

Here are two potential solutions:
- Have the CRM be the _deployable unit_, and allow ACEs to override parameters at runtime. This has the disadvantage that there is now a discrepancy between what the CRM defines and what is actually being executed.
- Have the CRM be the _deployable unit_ and introduce _another_ CRM as the _executable unit_ (which may or may not be identical to the _deployable unit_); the ACE consumes a CRM and then must generate a new CRM (overriding/extending whatever parameters it desires) to execute. This retains the advantage of the CRM-that-is-executed being immutable, but introduces the potentially confusing discrepancy between the CRM supplied to the ACE (deployable unit) and the CRM that is actually run (executable unit).

**Comment by cdaylward** [comment]
Consider the following basic toolchains:
* A minimal CLI tool that accepts a raw JSON CRM as input and executes the container specified therein.
* A more flexible CLI tool (e.g. Rocket) that takes command line arguments and determines what CRM to generate.
* CRM as a "task" specification submitted to a large...elastic compute environment.

In these toolchains, if a "user" (human or software) has specified what should be executed and under what constraints (resources available/isolation), and the ACE is free under the specification to "do other things", this seems to devalue the specification. If what is declared in the CRM does not reflect the behavior of the system, then we are just talking about a particular shared JSON schema (which does of course still have some value). Some of the value of a specification comes from being able to say that a particular implementation is compliant or non-compliant (or defective). If a CRM is merely advisory, this opens the door to all sorts of unexpected behavior.

The CRM should be a _contract_ for the ACE. The ACE therefore can either satisfy the constraints in the CRM or not (abort). _How_ they are satisfied would remain an implementation detail. If the CRM is a contract, understanding why expected and actual behavior might differ in the field would certainly be easier to track down for developers and administrators. The CRM would be inspectable and the actual behavior is observable.

If, for instance, a CRM is executed with incorrect memory isolation, it is easier to understand where the issue is if there is _not_ a side-channel that is configuring exceptional ACE behavior. Even under normal operation, if the ACE is free to modify execution that was outlined in the CRM, this creates a discrepancy between what "administrators know" and what "users expect", arguably something a specification should eliminate.

If a toolchain is required to provide additional or modified constraints in some production environment, generating a new/derivative CRM seems preferable. This could then be stored somewhere for inspection (perhaps some environments would wish to log all executed CRMs). Again, this makes clear _what was supposed to happen_. Such a scenario (needing to override a CRM), does not need to be part of the specification. This seems to be simply something a toolchain might do before hand-off to an ACE (CRM in, apply transform, new CRM out to ACE). It would then be up to a toolchain developer to decide how to handle a mismatch in capabilities provided by the ACE and declared in the CRM, e.g. feedback to user that the "ACE cannot do this, it can however do this, proceed?" I believe CRM-as-contract also still makes sense for under-/over-subscription models as well as dealing with unsupported isolators (although perhaps handling over-subscription and unsupported features could use some drawn-out examples.).

**Comment by philips** [comment]
I see the CRM as AN input to the ACE but it is very possible that command line flags, configuration files or environment variables in an environment can change the particular result of a run. Heck, the spec lets time creep in as an input too because example.com/myapp,channel=testing can mean something different tomorrow compared to today.

**Comment by cdaylward** [comment]
Seeing how the spec has evolved, and as the CRM doesn't actually have environment in it (they come along by way of the images alone in schema), my thinking on the use of the CRM might have been premature (apologies). Perhaps better to hammer out if there are two things here or not, first: "deployable unit" and/or "executable unit"...

**Comment by jonboulle** [comment]
This is addressed by #207

**Comment by jonboulle** [comment]
so happy to close
